language: java

jdk:
  - oraclejdk8
  - openjdk8

script:
  - mvn clean scala:compile compile package -DskipTests=true
  - ./run.sh

branches:
  only:
    - master

notifications:
  email: false