language: java

jdk:
- oraclejdk8
- openjdk8

script:
- mvn clean scala:compile compile package -DskipTests=true

branches:
  only:
  - master

notifications:
  email: false

before_deploy:
- openssl aes-256-cbc -K $encrypted_b044faba5aca_key -iv $encrypted_b044faba5aca_iv -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
- echo "StrictHostKeyChecking no" > ~/.ssh/config
- chmod +x deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master